# Pandas_ta studie

Deze pagina bevat tests en probeersels om te begrijpen hoe Pansas_ta werkt. Tevens bevat het enkele leermomenten om te weten hoe met Pandas dataframes om te gaan.

# Laden van data en tonen van de dataframe inhoud

In [27]:
import pandas as pd
import pandas_ta as ta

In [28]:
# Load data
df = pd.read_csv("./BTCUSDT_4h.csv")

In [29]:
# Reading columns
df.columns

Index(['# openTime', 'open', 'high', 'low', 'close', 'volume', 'closeTime',
       'qouteAssetVolume', 'numberOfTrades', 'takerBuyBaseAssetVolume',
       'takerBuyQuoteAssetVolume', 'ignore'],
      dtype='object')

In [30]:
# Watch first 5 entries
df.head(5)

,# openTime,open,high,low,close,volume,closeTime,qouteAssetVolume,numberOfTrades,takerBuyBaseAssetVolume,takerBuyQuoteAssetVolume,ignore
0,1595923200000,10881.62,11023.00,10565.00,10983.90,24850.974219,1595937599999,2.683766e+08,320922,11668.747362,1.260467e+08,0
1,1595937600000,10983.89,11180.00,10907.00,11150.26,18944.351192,1595951999999,2.092640e+08,279740,9341.771491,1.031928e+08,0
2,1595952000000,11150.25,11176.61,10840.00,10993.97,15746.845271,1595966399999,1.728165e+08,253636,7751.434897,8.508701e+07,0
3,1595966400000,10993.98,11050.00,10856.17,10906.27,7229.776972,1595980799999,7.924985e+07,152177,3356.673127,3.680286e+07,0
4,1595980800000,10906.27,11000.00,10831.55,10978.27,8288.755464,1595995199999,9.050050e+07,132996,3332.522510,3.638990e+07,0

## Starten met enkele simpele TA voorbeelden

In [31]:
# Calculate Returns and append to the df DataFrame
df.ta.log_return(cumulative=True, append=True)
df.ta.percent_return(cumulative=True, append=True)

0           NaN
1      0.015146
2      0.001129
3     -0.006848
4     -0.000246
         ...
495    0.067331
496    0.059817
497    0.063819
498    0.065093
499    0.080180
Name: CUMPCTRET_1, Length: 500, dtype: float64

In [32]:
df.columns

Index(['# openTime', 'open', 'high', 'low', 'close', 'volume', 'closeTime',
       'qouteAssetVolume', 'numberOfTrades', 'takerBuyBaseAssetVolume',
       'takerBuyQuoteAssetVolume', 'ignore', 'CUMLOGRET_1', 'CUMPCTRET_1'],
      dtype='object')

In [33]:
# show last 5 entries
df.tail(5)

,# openTime,open,high,low,close,volume,closeTime,qouteAssetVolume,numberOfTrades,takerBuyBaseAssetVolume,takerBuyQuoteAssetVolume,ignore,CUMLOGRET_1,CUMPCTRET_1
495,1603051200000,11432.23,11505.00,11413.96,11503.14,3787.003311,1603065599999,4.342609e+07,52589,2234.446172,2.563606e+07,0,0.046189,0.067331
496,1603065600000,11503.14,11535.00,11407.96,11416.71,5106.702706,1603079999999,5.854930e+07,74255,2345.392354,2.689825e+07,0,0.038648,0.059817
497,1603080000000,11416.25,11467.10,11407.96,11462.39,4137.008630,1603094399999,4.734594e+07,56586,1875.752040,2.146759e+07,0,0.042641,0.063819
498,1603094400000,11462.39,11532.01,11447.23,11477.00,5876.872361,1603108799999,6.746156e+07,72263,2801.044119,3.215728e+07,0,0.043914,0.065093
499,1603108800000,11477.00,11671.81,11472.46,11650.15,8515.296375,1603123199999,9.865727e+07,98840,5183.077239,6.004271e+07,0,0.058888,0.080180

## Help files

In [34]:
# Help about this, 'ta', extension
help(df.ta)

Help on AnalysisIndicators in module pandas_ta.core object:

class AnalysisIndicators(BasePandasObject)
 |  AnalysisIndicators(df, **kwargs)
 |
 |  AnalysisIndicators is a class that extends the Pandas DataFrame via
 |  Pandas @pd.api.extensions.register_dataframe_accessor('name') decorator.
 |
 |  This Pandas Extension is named 'ta' for Technical Analysis that allows us
 |  to apply technical indicators by extension.  Even though 'ta' is a
 |  Pandas DataFrame Extension, you can still call the Indicators
 |  individually. Use help() if needed.
 |
 |  By default the 'ta' extension uses lower case column names: open, high,
 |  low, close, and volume.  You can override the defaults by providing the
 |  it's replacement name when calling the indicator.  For example, to call the indicator hl2().
 |
 |  With 'default' columns: open, high, low, close, and volume.
 |  >>> df.ta.hl2()
 |  >>> df.ta(kind="hl2")
 |
 |  With DataFrame columns: Open, High, Low, Close, and Volume.
 |  >>> df.ta.hl2(high="High", low="Low")
 |  >>> df.ta(kind="hl2", high="High", low="Low")
 |
 |  If you do not want to use a DataFrame Extension, just call it normally.
 |  >>> sma10 = ta.sma(df["Close"]) # Default length=10
 |  >>> sma50 = ta.sma(df["Close"], length=50)
 |  >>> ichimoku, span = ta.ichimoku(df["High"], df["Low"], df["Close"])
 |
 |  Args:
 |      kind (str, optional): Default: None.  Kind is the 'name' of the indicator.
 |          It converts kind to lowercase before calling.
 |      timed (bool, optional): Default: False.  Curious about the execution
 |          speed?
 |      kwargs: Extension specific modifiers.
 |          append (bool, optional):  Default: False.  When True, it appends the
 |          resultant column(s) to the DataFrame.
 |
 |  Returns:
 |      Most Indicators will return a Pandas Series.  Others like MACD, BBANDS,
 |      KC, et al will return a Pandas DataFrame.  Ichimoku on the other hand
 |      will return two DataFrames, the Ichimoku DataFrame for the known period
 |      and a Span DataFrame for the future of the Span values.
 |
 |  Let's get started!
 |
 |  1. Loading the 'ta' module:
 |  >>> import pandas as pd
 |  >>> import ta as ta
 |
 |  2. Load some data:
 |  >>> df = pd.read_csv("AAPL.csv", index_col="date", parse_dates=True)
 |
 |  3. Help!
 |  3a. General Help:
 |  >>> help(df.ta)
 |  >>> df.ta()
 |  3b. Indicator Help:
 |  >>> help(ta.apo)
 |  3c. Indicator Extension Help:
 |  >>> help(df.ta.apo)
 |
 |  4. Ways of calling an indicator.
 |  4a. Calling just the MACD indicator without "ta" DataFrame extension.
 |  >>> ta.apo(df["close"])
 |  4b. Calling just the MACD indicator with "ta" DataFrame extension.
 |  >>> df.ta.apo()
 |  4c. Calling using kind.
 |  >>> df.ta(kind="apo")
 |
 |  5. Working with kwargs
 |  5a. Append the result to the working df.
 |  >>> df.ta.apo(append=True)
 |  5b. Timing an indicator.
 |  >>> apo = df.ta(kind="apo", timed=True)
 |  >>> print(apo.timed)
 |
 |  Method resolution order:
 |      AnalysisIndicators
 |      BasePandasObject
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __call__(self, kind: str = None, alias: str = None, timed: bool = False, verbose: bool = False, **kwargs)
 |      Call self as a function.
 |
 |  aberration(self, length=None, atr_length=None, offset=None, **kwargs)
 |      # Volatility
 |
 |  above(self, asint=True, offset=None, **kwargs)
 |      # Utility
 |
 |  above_value(self, value=None, asint=True, offset=None, **kwargs)
 |
 |  accbands(self, length=None, c=None, mamode=None, offset=None, **kwargs)
 |
 |  ad(self, open_=None, signed=True, offset=None, **kwargs)
 |      # Volume
 |
 |  adosc(self, open_=None, fast=None, slow=None, signed=True, offset=None, **kwargs)
 |
 |  adx(self, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |      # Trend
 |
 |  amat(self, fast=None, slow=None, mamode=None, lookback=None, offset=None, **kwargs)
 |
 |  ao(self, fast=None, slow=None, offset=None, **kwargs)
 |      # Momentum
 |
 |  aobv(self, fast=None, slow=None, mamode=None, max_lookback=None, min_lookback=None, offset=None, **kwargs)
 |
 |  apo(self, fast=None, slow=None, offset=None, **kwargs)
 |
 |  aroon(self, length=None, scalar=None, offset=None, **kwargs)
 |
 |  atr(self, length=None, mamode=None, offset=None, **kwargs)
 |
 |  bbands(self, length=None, std=None, mamode=None, offset=None, **kwargs)
 |
 |  below(self, asint=True, offset=None, **kwargs)
 |
 |  below_value(self, value=None, asint=True, offset=None, **kwargs)
 |
 |  bias(self, length=None, mamode=None, offset=None, **kwargs)
 |
 |  bop(self, percentage=False, offset=None, **kwargs)
 |
 |  brar(self, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  cci(self, length=None, c=None, offset=None, **kwargs)
 |
 |  cdl_doji(self, offset=None, **kwargs)
 |      # Public DataFrame Methods: Indicators and Utilities
 |      # Candles
 |
 |  cdl_inside(self, offset=None, **kwargs)
 |
 |  cfo(self, length=None, offset=None, **kwargs)
 |
 |  cg(self, length=None, offset=None, **kwargs)
 |
 |  chop(self, length=None, atr_length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  cksp(self, p=None, x=None, q=None, offset=None, **kwargs)
 |
 |  cmf(self, open_=None, length=None, offset=None, **kwargs)
 |
 |  cmo(self, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  constants(self, append: bool, values: list)
 |      Constants
 |
 |      Add or remove constants to the DataFrame easily with Numpy's arrays or
 |      lists. Useful when you need easily accessible horizontal lines for
 |      charting.
 |
 |      Add constant '1' to the DataFrame
 |      >>> df.ta.constants(True, [1])
 |      Remove constant '1' to the DataFrame
 |      >>> df.ta.constants(False, [1])
 |
 |      Adding the constants for the charts
 |      >>> import numpy as np
 |      >>> chart_lines = np.append(np.arange(-4, 5, 1), np.arange(-100, 110, 10))
 |      >>> df.ta.constants(True, chart_lines)
 |      Removing some constants from the DataFrame
 |      >>> df.ta.constants(False, np.array([-60, -40, 40, 60]))
 |
 |      Args:
 |          append (bool): If True, appends a Numpy range of constants to the
 |              working DataFrame.  If False, it removes the constant range from
 |              the working DataFrame. Default: None.
 |
 |      Returns:
 |          Returns the appended constants
 |          Returns nothing to the user.  Either adds or removes constant ranges
 |          from the working DataFrame.
 |
 |  coppock(self, length=None, fast=None, slow=None, offset=None, **kwargs)
 |
 |  cross(self, above=True, asint=True, offset=None, **kwargs)
 |
 |  cross_value(self, value=None, above=True, asint=True, offset=None, **kwargs)
 |
 |  decay(self, length=None, mode=None, offset=None, **kwargs)
 |
 |  decreasing(self, length=None, asint=True, offset=None, **kwargs)
 |
 |  dema(self, length=None, offset=None, **kwargs)
 |      # Overlap
 |
 |  donchian(self, lower_length=None, upper_length=None, offset=None, **kwargs)
 |
 |  dpo(self, length=None, centered=True, offset=None, **kwargs)
 |
 |  efi(self, length=None, mamode=None, offset=None, drift=None, **kwargs)
 |
 |  ema(self, length=None, offset=None, **kwargs)
 |
 |  entropy(self, length=None, base=None, offset=None, **kwargs)
 |      # Statistics
 |
 |  eom(self, length=None, divisor=None, offset=None, drift=None, **kwargs)
 |
 |  er(self, length=None, drift=None, offset=None, **kwargs)
 |
 |  eri(self, length=None, offset=None, **kwargs)
 |
 |  fisher(self, length=None, signal=None, offset=None, **kwargs)
 |
 |  fwma(self, length=None, offset=None, **kwargs)
 |
 |  ha(self, offset=None, **kwargs)
 |
 |  hilo(self, high_length=None, low_length=None, mamode=None, offset=None, **kwargs)
 |
 |  hl2(self, offset=None, **kwargs)
 |
 |  hlc3(self, offset=None, **kwargs)
 |
 |  hma(self, length=None, offset=None, **kwargs)
 |
 |  ichimoku(self, tenkan=None, kijun=None, senkou=None, offset=None, **kwargs)
 |
 |  increasing(self, length=None, asint=True, offset=None, **kwargs)
 |
 |  indicators(self, **kwargs)
 |      List of Indicators
 |
 |      Args:
 |          kwargs:
 |              as_list (bool, optional):  Default: False.  When True, it
 |                  returns a list of the indicators.
 |              exclude (list, optional):  Default: None.  The passed in list
 |                  will be excluded from the indicators list.
 |
 |      Returns:
 |          Prints the list of indicators. If as_list=True, then a list.
 |
 |  inertia(self, length=None, rvi_length=None, scalar=None, refined=None, thirds=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  kama(self, length=None, fast=None, slow=None, offset=None, **kwargs)
 |
 |  kc(self, length=None, scalar=None, mamode=None, offset=None, **kwargs)
 |
 |  kdj(self, length=None, signal=None, offset=None, **kwargs)
 |
 |  kst(self, roc1=None, roc2=None, roc3=None, roc4=None, sma1=None, sma2=None, sma3=None, sma4=None, signal=None, offset=None, **kwargs)
 |
 |  kurtosis(self, length=None, offset=None, **kwargs)
 |
 |  linreg(self, length=None, offset=None, adjust=None, **kwargs)
 |
 |  log_return(self, length=None, cumulative=False, percent=False, offset=None, **kwargs)
 |      # Performance
 |
 |  long_run(self, fast=None, slow=None, length=None, offset=None, **kwargs)
 |
 |  macd(self, fast=None, slow=None, signal=None, offset=None, **kwargs)
 |
 |  mad(self, length=None, offset=None, **kwargs)
 |
 |  massi(self, fast=None, slow=None, offset=None, **kwargs)
 |
 |  median(self, length=None, offset=None, **kwargs)
 |
 |  mfi(self, length=None, drift=None, offset=None, **kwargs)
 |
 |  midpoint(self, length=None, offset=None, **kwargs)
 |
 |  midprice(self, length=None, offset=None, **kwargs)
 |
 |  mom(self, length=None, offset=None, **kwargs)
 |
 |  natr(self, length=None, mamode=None, scalar=None, offset=None, **kwargs)
 |
 |  nvi(self, length=None, initial=None, signed=True, offset=None, **kwargs)
 |
 |  obv(self, offset=None, **kwargs)
 |
 |  ohlc4(self, offset=None, **kwargs)
 |
 |  pdist(self, drift=None, offset=None, **kwargs)
 |
 |  percent_return(self, length=None, cumulative=False, percent=False, offset=None, **kwargs)
 |
 |  pgo(self, length=None, offset=None, **kwargs)
 |
 |  ppo(self, fast=None, slow=None, scalar=None, offset=None, **kwargs)
 |
 |  psar(self, af=None, max_af=None, offset=None, **kwargs)
 |
 |  psl(self, open_=None, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  pvi(self, length=None, initial=None, signed=True, offset=None, **kwargs)
 |
 |  pvo(self, fast=None, slow=None, signal=None, scalar=None, offset=None, **kwargs)
 |
 |  pvol(self, volume=None, offset=None, **kwargs)
 |
 |  pvt(self, offset=None, **kwargs)
 |
 |  pwma(self, length=None, offset=None, **kwargs)
 |
 |  qstick(self, length=None, offset=None, **kwargs)
 |
 |  quantile(self, length=None, q=None, offset=None, **kwargs)
 |
 |  rma(self, length=None, offset=None, **kwargs)
 |
 |  roc(self, length=None, offset=None, **kwargs)
 |
 |  rsi(self, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  rvgi(self, length=None, swma_length=None, offset=None, **kwargs)
 |
 |  rvi(self, length=None, scalar=None, refined=None, thirds=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  short_run(self, fast=None, slow=None, length=None, offset=None, **kwargs)
 |
 |  sinwma(self, length=None, offset=None, **kwargs)
 |
 |  skew(self, length=None, offset=None, **kwargs)
 |
 |  slope(self, length=None, offset=None, **kwargs)
 |
 |  sma(self, length=None, offset=None, **kwargs)
 |
 |  smi(self, fast=None, slow=None, signal=None, scalar=None, offset=None, **kwargs)
 |
 |  squeeze(self, bb_length=None, bb_std=None, kc_length=None, kc_scalar=None, mom_length=None, mom_smooth=None, use_tr=None, offset=None, **kwargs)
 |
 |  stdev(self, length=None, offset=None, **kwargs)
 |
 |  stoch(self, fast_k=None, slow_k=None, slow_d=None, offset=None, **kwargs)
 |
 |  stochrsi(self, length=None, rsi_length=None, k=None, d=None, offset=None, **kwargs)
 |
 |  strategy(self, *args, **kwargs)
 |      Strategy Method
 |
 |      An experimental method that by default runs all applicable indicators.
 |      Future implementations will allow more specific indicator generation through
 |      a json config file.
 |
 |      Args:
 |          name (str, optional): Default: "all"
 |          exclude (list, optional): Default: []. List of indicator names to exclude.
 |
 |          kwargs:
 |              (optional) Default: {}. Any indicator argument you want to modify.
 |                  For example, length=20 or offset=-1 or high=df["high"] ...
 |
 |  supertrend(self, period=None, multiplier=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  swma(self, length=None, offset=None, **kwargs)
 |
 |  t3(self, length=None, a=None, offset=None, **kwargs)
 |
 |  tema(self, length=None, offset=None, **kwargs)
 |
 |  thermo(self, long=None, short=None, length=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  trend_return(self, trend=None, log=True, cumulative=None, offset=None, trend_reset=None, **kwargs)
 |
 |  trima(self, length=None, offset=None, **kwargs)
 |
 |  trix(self, length=None, signal=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  true_range(self, drift=None, offset=None, **kwargs)
 |
 |  tsi(self, fast=None, slow=None, drift=None, offset=None, **kwargs)
 |
 |  ttm_trend(self, length=None, offset=None, **kwargs)
 |
 |  ui(self, length=None, scalar=None, offset=None, **kwargs)
 |
 |  uo(self, fast=None, medium=None, slow=None, fast_w=None, medium_w=None, slow_w=None, drift=None, offset=None, **kwargs)
 |
 |  variance(self, length=None, offset=None, **kwargs)
 |
 |  vortex(self, drift=None, offset=None, **kwargs)
 |
 |  vp(self, width=None, percent=None, **kwargs)
 |
 |  vwap(self, offset=None, **kwargs)
 |
 |  vwma(self, volume=None, length=None, offset=None, **kwargs)
 |
 |  wcp(self, offset=None, **kwargs)
 |
 |  willr(self, length=None, percentage=True, offset=None, **kwargs)
 |
 |  wma(self, length=None, offset=None, **kwargs)
 |
 |  zlma(self, length=None, mamode=None, offset=None, **kwargs)
 |
 |  zscore(self, length=None, std=None, offset=None, **kwargs)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties defined here:
 |
 |  categories
 |      Returns the categories.
 |
 |  datetime_ordered
 |      Returns True if the index is a datetime and ordered.
 |
 |  reverse
 |      Reverses the DataFrame. Simply: df.iloc[::-1]
 |
 |  version
 |      Returns the version.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  adjusted
 |      property: df.ta.adjusted
 |
 |  cores
 |      Returns the categories.
 |
 |  mp
 |      property: df.ta.mp
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from BasePandasObject:
 |
 |  __init__(self, df, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pandas.core.base.PandasObject:
 |
 |  __repr__(self) -> str
 |      Return a string representation for a particular object.
 |
 |  __sizeof__(self)
 |      Generates the total memory usage for an object that returns
 |      either a value or Series of values
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from pandas.core.base.PandasObject:
 |
 |  __annotations__ = {'_cache': typing.Dict[str, typing.Any]}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pandas.core.accessor.DirNamesMixin:
 |
 |  __dir__(self)
 |      Provide method name lookup and completion.
 |
 |      Notes
 |      -----
 |      Only provide 'public' methods.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from pandas.core.accessor.DirNamesMixin:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [5]:
# Help on SMA
help(ta.sma)

NameError: name 'ta' is not defined

In [35]:
# Indicator Help:
help(ta.apo)

Help on function apo in module pandas_ta.momentum.apo:

apo(close, fast=None, slow=None, offset=None, **kwargs)
    Absolute Price Oscillator (APO)

    The Absolute Price Oscillator is an indicator used to measure a security's
    momentum.  It is simply the difference of two Exponential Moving Averages
    (EMA) of two different periods.  Note: APO and MACD lines are equivalent.

    Sources:
        https://www.tradingtechnologies.com/xtrader-help/x-study/technical-indicator-definitions/absolute-price-oscillator-apo/

    Calculation:
        Default Inputs:
            fast=12, slow=26
        SMA = Simple Moving Average
        APO = SMA(close, fast) - SMA(close, slow)

    Args:
        close (pd.Series): Series of 'close's
        fast (int): The short period.  Default: 12
        slow (int): The long period.   Default: 26
        offset (int): How many periods to offset the result.  Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method

    Returns:
        pd.Series: New feature generated.

In [36]:
# Indicator Extension Help:
help(df.ta.apo)

Help on method apo in module pandas_ta.core:

apo(fast=None, slow=None, offset=None, **kwargs) method of pandas_ta.core.AnalysisIndicators instance

In [37]:
# List of all indicators
df.ta.indicators()

Pandas TA - Technical Analysis Indicators - v0.2.23b0
Total Indicators: 123
Abbreviations:
    aberration, above, above_value, accbands, ad, adosc, adx, amat, ao, aobv, apo, aroon, atr, bbands, below, below_value, bias, bop, brar, cci, cdl_doji, cdl_inside, cfo, cg, chop, cksp, cmf, cmo, coppock, cross, cross_value, decay, decreasing, dema, donchian, dpo, efi, ema, entropy, eom, er, eri, fisher, fwma, ha, hilo, hl2, hlc3, hma, ichimoku, increasing, inertia, kama, kc, kdj, kst, kurtosis, linreg, log_return, long_run, macd, mad, massi, median, mfi, midpoint, midprice, mom, natr, nvi, obv, ohlc4, pdist, percent_return, pgo, ppo, psar, psl, pvi, pvo, pvol, pvt, pwma, qstick, quantile, rma, roc, rsi, rvgi, rvi, short_run, sinwma, skew, slope, sma, smi, squeeze, stdev, stoch, stochrsi, supertrend, swma, t3, tema, thermo, trend_return, trima, trix, true_range, tsi, ttm_trend, ui, uo, variance, vortex, vp, vwap, vwma, wcp, willr, wma, zlma, zscore

In [38]:
# Help about the log_return indicator
help(ta.log_return)

Help on function log_return in module pandas_ta.performance.log_return:

log_return(close, length=None, cumulative=False, offset=None, **kwargs)
    Log Return

    Calculates the logarithmic return of a Series.
    See also: help(df.ta.log_return) for additional **kwargs a valid 'df'.

    Sources:
        https://stackoverflow.com/questions/31287552/logarithmic-returns-in-pandas-dataframe

    Calculation:
        Default Inputs:
            length=1, cumulative=False
        LOGRET = log( close.diff(periods=length) )
        CUMLOGRET = LOGRET.cumsum() if cumulative

    Args:
        close (pd.Series): Series of 'close's
        length (int): It's period.  Default: 20
        cumulative (bool): If True, returns the cumulative returns.  Default: False
        offset (int): How many periods to offset the result.  Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method

    Returns:
        pd.Series: New feature generated.

# Starten met eigen probeersels

## SMA 23

In [53]:
# Returning a series with SMA23
sma23 = ta.sma(df["close"], length=23)
print(sma23)

0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
           ...
495    11391.106087
496    11391.970435
497    11398.362609
498    11401.787826
499    11407.406087
Name: SMA_23, Length: 500, dtype: float64

In [41]:
# appending the results directly to the DataFrame
df.ta.sma(length=23, append=True)

0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
           ...
495    11391.106087
496    11391.970435
497    11398.362609
498    11401.787826
499    11407.406087
Name: SMA_23, Length: 500, dtype: float64

In [50]:
df.columns

Index(['# openTime', 'open', 'high', 'low', 'close', 'volume', 'closeTime',
       'qouteAssetVolume', 'numberOfTrades', 'takerBuyBaseAssetVolume',
       'takerBuyQuoteAssetVolume', 'ignore', 'CUMLOGRET_1', 'CUMPCTRET_1',
       'SMA_23'],
      dtype='object')

## Specifieke kolommen printen

LET OP! Meerdere kolommen printen kan alleen als je deze in een array plaatst [['1','2',''3]] etc.

In [54]:
df[['# openTime', 'open', 'high', 'low', 'close', 'volume','SMA_23']].tail(10)

,# openTime,open,high,low,close,volume,SMA_23
490,1602979200000,11360.31,11398.00,11346.22,11368.02,3109.800004,11372.180000
491,1602993600000,11368.02,11464.99,11366.87,11455.40,4133.080675,11376.200870
492,1603008000000,11455.40,11477.96,11398.41,11420.62,3767.885698,11380.542609
493,1603022400000,11420.62,11482.24,11407.61,11446.68,5024.660598,11385.083043
494,1603036800000,11447.05,11478.47,11429.88,11432.24,3461.610905,11385.706957
495,1603051200000,11432.23,11505.00,11413.96,11503.14,3787.003311,11391.106087
496,1603065600000,11503.14,11535.00,11407.96,11416.71,5106.702706,11391.970435
497,1603080000000,11416.25,11467.10,11407.96,11462.39,4137.008630,11398.362609
498,1603094400000,11462.39,11532.01,11447.23,11477.00,5876.872361,11401.787826
499,1603108800000,11477.00,11671.81,11472.46,11650.15,8515.296375,11407.406087

Verander openTime en closeTime in leesbaar formaat (werkt echter niet door naar DF...)

In [57]:
# verander # OpenTime column naam
df.rename(columns = {"# openTime":"openTime"})

,openTime,open,high,low,close,volume,closeTime,qouteAssetVolume,numberOfTrades,takerBuyBaseAssetVolume,takerBuyQuoteAssetVolume,ignore,CUMLOGRET_1,CUMPCTRET_1,SMA_23
0,1595923200000,10881.62,11023.00,10565.00,10983.90,24850.974219,1595937599999,2.683766e+08,320922,11668.747362,1.260467e+08,0,NaN,NaN,NaN
1,1595937600000,10983.89,11180.00,10907.00,11150.26,18944.351192,1595951999999,2.092640e+08,279740,9341.771491,1.031928e+08,0,0.015032,0.015146,NaN
2,1595952000000,11150.25,11176.61,10840.00,10993.97,15746.845271,1595966399999,1.728165e+08,253636,7751.434897,8.508701e+07,0,0.000916,0.001129,NaN
3,1595966400000,10993.98,11050.00,10856.17,10906.27,7229.776972,1595980799999,7.924985e+07,152177,3356.673127,3.680286e+07,0,-0.007093,-0.006848,NaN
4,1595980800000,10906.27,11000.00,10831.55,10978.27,8288.755464,1595995199999,9.050050e+07,132996,3332.522510,3.638990e+07,0,-0.000513,-0.000246,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1603051200000,11432.23,11505.00,11413.96,11503.14,3787.003311,1603065599999,4.342609e+07,52589,2234.446172,2.563606e+07,0,0.046189,0.067331,11391.106087
496,1603065600000,11503.14,11535.00,11407.96,11416.71,5106.702706,1603079999999,5.854930e+07,74255,2345.392354,2.689825e+07,0,0.038648,0.059817,11391.970435
497,1603080000000,11416.25,11467.10,11407.96,11462.39,4137.008630,1603094399999,4.734594e+07,56586,1875.752040,2.146759e+07,0,0.042641,0.063819,11398.362609
498,1603094400000,11462.39,11532.01,11447.23,11477.00,5876.872361,1603108799999,6.746156e+07,72263,2801.044119,3.215728e+07,0,0.043914,0.065093,11401.787826
499,1603108800000,11477.00,11671.81,11472.46,11650.15,8515.296375,1603123199999,9.865727e+07,98840,5183.077239,6.004271e+07,0,0.058888,0.080180,11407.406087

#### Aanpassen van Unix dateTime format naar leesbaar format

In [67]:
df['# openTime']=(pd.to_datetime(df['# openTime'],unit='ms'))
df['closeTime']=(pd.to_datetime(df['closeTime'],unit='ms'))

In [71]:
df[['# openTime', 'open', 'high', 'low', 'close', 'volume','SMA_23']].tail(10)

,# openTime,open,high,low,close,volume,SMA_23
490,2020-10-18 00:00:00,11360.31,11398.00,11346.22,11368.02,3109.800004,11372.180000
491,2020-10-18 04:00:00,11368.02,11464.99,11366.87,11455.40,4133.080675,11376.200870
492,2020-10-18 08:00:00,11455.40,11477.96,11398.41,11420.62,3767.885698,11380.542609
493,2020-10-18 12:00:00,11420.62,11482.24,11407.61,11446.68,5024.660598,11385.083043
494,2020-10-18 16:00:00,11447.05,11478.47,11429.88,11432.24,3461.610905,11385.706957
495,2020-10-18 20:00:00,11432.23,11505.00,11413.96,11503.14,3787.003311,11391.106087
496,2020-10-19 00:00:00,11503.14,11535.00,11407.96,11416.71,5106.702706,11391.970435
497,2020-10-19 04:00:00,11416.25,11467.10,11407.96,11462.39,4137.008630,11398.362609
498,2020-10-19 08:00:00,11462.39,11532.01,11447.23,11477.00,5876.872361,11401.787826
499,2020-10-19 12:00:00,11477.00,11671.81,11472.46,11650.15,8515.296375,11407.406087

![Tradingview](./09-25-38.png)

SMA 23 data lijkt te kloppen met die van Tradingview. Dezelfde waarden gezien op de chart.



## Money Flow index toevoegen

In [81]:
help(ta.mfi)

Help on function mfi in module pandas_ta.volume.mfi:

mfi(high, low, close, volume, length=None, drift=None, offset=None, **kwargs)
    Money Flow Index (MFI)

    Money Flow Index is an oscillator indicator that is used to measure buying and
    selling pressure by utilizing both price and volume.

    Sources:
        https://www.tradingview.com/wiki/Money_Flow_(MFI)

    Calculation:
        Default Inputs:
            length=14, drift=1
        tp = typical_price = hlc3 = (high + low + close) / 3
        rmf = raw_money_flow = tp * volume

        pmf = pos_money_flow = SUM(rmf, length) if tp.diff(drift) > 0 else 0
        nmf = neg_money_flow = SUM(rmf, length) if tp.diff(drift) < 0 else 0

        MFR = money_flow_ratio = pmf / nmf
        MFI = money_flow_index = 100 * pmf / (pmf + nmf)

    Args:
        high (pd.Series): Series of 'high's
        low (pd.Series): Series of 'low's
        close (pd.Series): Series of 'close's
        volume (pd.Series): Series of 'volume's
        length (int): The sum period.  Default: 14
        drift (int): The difference period.   Default: 1
        offset (int): How many periods to offset the result.  Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method

    Returns:
        pd.Series: New feature generated.

In [98]:
# Returning a series with SMA23
mfi14 = ta.mfi(df['high'],df['low'],df['close'],df['volume'], length=14)
print(mfi14)

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
         ...
495    64.532976
496    64.681923
497    64.765647
498    66.052030
499    69.299820
Name: MFI_14, Length: 500, dtype: float64

In [103]:
# appending the results directly to the DataFrame
df.ta.mfi(length=14, append=True)

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
         ...
495    64.532976
496    64.681923
497    64.765647
498    66.052030
499    69.299820
Name: MFI_14, Length: 500, dtype: float64

In [124]:
df.columns

Index(['# openTime', 'open', 'high', 'low', 'close', 'volume', 'closeTime',
       'qouteAssetVolume', 'numberOfTrades', 'takerBuyBaseAssetVolume',
       'takerBuyQuoteAssetVolume', 'ignore', 'CUMLOGRET_1', 'CUMPCTRET_1',
       'SMA_23', 'CMO_14', 'MFI_14', 'RSI_14', 'SMA_pos', 'MFI_pos', 'CMO_pos',
       'RSI_pos'],
      dtype='object')

In [125]:
df[['# openTime', 'open', 'high', 'low', 'close', 'volume','SMA_23','MFI_14']].tail(25)

,# openTime,open,high,low,close,volume,SMA_23,MFI_14
475,2020-10-15 12:00:00,11315.38,11416.15,11275.01,11398.22,9317.518702,11405.683043,30.848396
476,2020-10-15 16:00:00,11398.60,11535.00,11363.37,11520.93,11112.811228,11412.287826,32.915090
477,2020-10-15 20:00:00,11520.93,11617.34,11400.86,11505.12,9070.137184,11417.510435,42.639683
478,2020-10-16 00:00:00,11505.13,11541.15,11470.00,11507.97,4320.834251,11423.103043,43.771627
479,2020-10-16 04:00:00,11507.97,11507.97,11200.00,11305.87,17084.872694,11425.775217,35.133883
480,2020-10-16 08:00:00,11305.87,11397.18,11212.00,11369.34,10724.889126,11417.947391,33.192991
481,2020-10-16 12:00:00,11369.27,11394.69,11281.65,11331.19,7118.295911,11408.567391,38.670238
482,2020-10-16 16:00:00,11331.19,11367.91,11299.87,11308.11,5292.071516,11398.996087,39.000597
483,2020-10-16 20:00:00,11308.23,11349.00,11273.75,11319.32,4256.786004,11392.956087,42.243950
484,2020-10-17 00:00:00,11319.24,11363.26,11272.48,11363.01,3863.795573,11389.086957,47.463744
485,2020-10-17 04:00:00,11363.00,11379.92,11334.61,11344.98,2647.551495,11382.940000,46.607468
486,2020-10-17 08:00:00,11344.99,11358.88,11308.63,11343.13,3658.009377,11381.113043,46.917100
487,2020-10-17 12:00:00,11343.29,11402.42,11255.00,11337.54,6456.072787,11378.926522,41.375335
488,2020-10-17 16:00:00,11337.54,11360.00,11300.00,11342.21,3215.975787,11375.520000,47.362826
489,2020-10-17 20:00:00,11342.21,11373.18,11325.00,11360.20,2527.510222,11374.224348,43.453359
490,2020-10-18 00:00:00,11360.31,11398.00,11346.22,11368.02,3109.800004,11372.180000,37.951933
491,2020-10-18 04:00:00,11368.02,11464.99,11366.87,11455.40,4133.080675,11376.200870,33.967882
492,2020-10-18 08:00:00,11455.40,11477.96,11398.41,11420.62,3767.885698,11380.542609,39.100197
493,2020-10-18 12:00:00,11420.62,11482.24,11407.61,11446.68,5024.660598,11385.083043,53.926719
494,2020-10-18 16:00:00,11447.05,11478.47,11429.88,11432.24,3461.610905,11385.706957,66.518471
495,2020-10-18 20:00:00,11432.23,11505.00,11413.96,11503.14,3787.003311,11391.106087,64.532976
496,2020-10-19 00:00:00,11503.14,11535.00,11407.96,11416.71,5106.702706,11391.970435,64.681923
497,2020-10-19 04:00:00,11416.25,11467.10,11407.96,11462.39,4137.008630,11398.362609,64.765647
498,2020-10-19 08:00:00,11462.39,11532.01,11447.23,11477.00,5876.872361,11401.787826,66.052030
499,2020-10-19 12:00:00,11477.00,11671.81,11472.46,11650.15,8515.296375,11407.406087,69.299820

## RSI toevoegen

In [108]:
rsi14 = ta.rsi(df["close"], length=14)
print(rsi14)

0             NaN
1      100.000000
2       49.708325
3       38.122427
4       48.694943
          ...
495     61.126118
496     52.437467
497     55.997463
498     57.103365
499     67.521533
Name: RSI_14, Length: 500, dtype: float64

In [109]:
# appending the results directly to the DataFrame
df.ta.rsi(length=14, append=True)

0             NaN
1      100.000000
2       49.708325
3       38.122427
4       48.694943
          ...
495     61.126118
496     52.437467
497     55.997463
498     57.103365
499     67.521533
Name: RSI_14, Length: 500, dtype: float64

In [131]:
del df['CMO_14']

In [133]:
df[['# openTime', 'open', 'high', 'low', 'close', 'volume','SMA_23','MFI_14','RSI_14']].tail(25)

,# openTime,open,high,low,close,volume,SMA_23,MFI_14,RSI_14
475,2020-10-15 12:00:00,11315.38,11416.15,11275.01,11398.22,9317.518702,11405.683043,30.848396,54.046610
476,2020-10-15 16:00:00,11398.60,11535.00,11363.37,11520.93,11112.811228,11412.287826,32.915090,61.086456
477,2020-10-15 20:00:00,11520.93,11617.34,11400.86,11505.12,9070.137184,11417.510435,42.639683,59.815026
478,2020-10-16 00:00:00,11505.13,11541.15,11470.00,11507.97,4320.834251,11423.103043,43.771627,59.976743
479,2020-10-16 04:00:00,11507.97,11507.97,11200.00,11305.87,17084.872694,11425.775217,35.133883,45.877400
480,2020-10-16 08:00:00,11305.87,11397.18,11212.00,11369.34,10724.889126,11417.947391,33.192991,49.863574
481,2020-10-16 12:00:00,11369.27,11394.69,11281.65,11331.19,7118.295911,11408.567391,38.670238,47.594518
482,2020-10-16 16:00:00,11331.19,11367.91,11299.87,11308.11,5292.071516,11398.996087,39.000597,46.224090
483,2020-10-16 20:00:00,11308.23,11349.00,11273.75,11319.32,4256.786004,11392.956087,42.243950,47.021992
484,2020-10-17 00:00:00,11319.24,11363.26,11272.48,11363.01,3863.795573,11389.086957,47.463744,50.127844
485,2020-10-17 04:00:00,11363.00,11379.92,11334.61,11344.98,2647.551495,11382.940000,46.607468,48.854950
486,2020-10-17 08:00:00,11344.99,11358.88,11308.63,11343.13,3658.009377,11381.113043,46.917100,48.718251
487,2020-10-17 12:00:00,11343.29,11402.42,11255.00,11337.54,6456.072787,11378.926522,41.375335,48.278672
488,2020-10-17 16:00:00,11337.54,11360.00,11300.00,11342.21,3215.975787,11375.520000,47.362826,48.695152
489,2020-10-17 20:00:00,11342.21,11373.18,11325.00,11360.20,2527.510222,11374.224348,43.453359,50.353632
490,2020-10-18 00:00:00,11360.31,11398.00,11346.22,11368.02,3109.800004,11372.180000,37.951933,51.093709
491,2020-10-18 04:00:00,11368.02,11464.99,11366.87,11455.40,4133.080675,11376.200870,33.967882,58.532280
492,2020-10-18 08:00:00,11455.40,11477.96,11398.41,11420.62,3767.885698,11380.542609,39.100197,54.949727
493,2020-10-18 12:00:00,11420.62,11482.24,11407.61,11446.68,5024.660598,11385.083043,53.926719,57.069980
494,2020-10-18 16:00:00,11447.05,11478.47,11429.88,11432.24,3461.610905,11385.706957,66.518471,55.510979
495,2020-10-18 20:00:00,11432.23,11505.00,11413.96,11503.14,3787.003311,11391.106087,64.532976,61.126118
496,2020-10-19 00:00:00,11503.14,11535.00,11407.96,11416.71,5106.702706,11391.970435,64.681923,52.437467
497,2020-10-19 04:00:00,11416.25,11467.10,11407.96,11462.39,4137.008630,11398.362609,64.765647,55.997463
498,2020-10-19 08:00:00,11462.39,11532.01,11447.23,11477.00,5876.872361,11401.787826,66.052030,57.103365
499,2020-10-19 12:00:00,11477.00,11671.81,11472.46,11650.15,8515.296375,11407.406087,69.299820,67.521533

## Kolommen toevoegen voor bepalen Long / Short positie

In [141]:
import numpy as np

# SMA check
df['SMA_pos'] = np.where(df['close']>df['SMA_23'], 'long' , 'short')
# MFI check
df['MFI_pos'] = np.where(df['MFI_14']>50, 'long', 'short')
# RSI check
df['RSI_pos'] = np.where(df['RSI_14']>55, 'long', 'short')

In [142]:
df[['# openTime','close','SMA_23','SMA_pos','MFI_14','MFI_pos','RSI_14','RSI_pos']].tail(10)

,# openTime,close,SMA_23,SMA_pos,MFI_14,MFI_pos,RSI_14,RSI_pos
490,2020-10-18 00:00:00,11368.02,11372.180000,short,37.951933,short,51.093709,short
491,2020-10-18 04:00:00,11455.40,11376.200870,long,33.967882,short,58.532280,long
492,2020-10-18 08:00:00,11420.62,11380.542609,long,39.100197,short,54.949727,short
493,2020-10-18 12:00:00,11446.68,11385.083043,long,53.926719,long,57.069980,long
494,2020-10-18 16:00:00,11432.24,11385.706957,long,66.518471,long,55.510979,long
495,2020-10-18 20:00:00,11503.14,11391.106087,long,64.532976,long,61.126118,long
496,2020-10-19 00:00:00,11416.71,11391.970435,long,64.681923,long,52.437467,short
497,2020-10-19 04:00:00,11462.39,11398.362609,long,64.765647,long,55.997463,long
498,2020-10-19 08:00:00,11477.00,11401.787826,long,66.052030,long,57.103365,long
499,2020-10-19 12:00:00,11650.15,11407.406087,long,69.299820,long,67.521533,long

## Add last column for checking if all conditions are 'long'

Eerst moeten de long en short condities omgezet worden in cijfers zodat deze opgeteld kunnen worden. 

0 = short  
1 = long  

Bij positie waarde 0 = short  
Bij positie waarde 1 = neutral  
Bij positie waarde 2 = warning  
Bij positie waarde 3 = long

In [144]:
# SMA check
df['SMA_pos'] = np.where(df['close']>df['SMA_23'], 1 , 0)
# MFI check
df['MFI_pos'] = np.where(df['MFI_14']>50, 1 , 0)
# RSI check
df['RSI_pos'] = np.where(df['RSI_14']>55, 1, 0)

df[['# openTime','close','SMA_23','SMA_pos','MFI_14','MFI_pos','RSI_14','RSI_pos']].tail(10)

,# openTime,close,SMA_23,SMA_pos,MFI_14,MFI_pos,RSI_14,RSI_pos
490,2020-10-18 00:00:00,11368.02,11372.180000,0,37.951933,0,51.093709,0
491,2020-10-18 04:00:00,11455.40,11376.200870,1,33.967882,0,58.532280,1
492,2020-10-18 08:00:00,11420.62,11380.542609,1,39.100197,0,54.949727,0
493,2020-10-18 12:00:00,11446.68,11385.083043,1,53.926719,1,57.069980,1
494,2020-10-18 16:00:00,11432.24,11385.706957,1,66.518471,1,55.510979,1
495,2020-10-18 20:00:00,11503.14,11391.106087,1,64.532976,1,61.126118,1
496,2020-10-19 00:00:00,11416.71,11391.970435,1,64.681923,1,52.437467,0
497,2020-10-19 04:00:00,11462.39,11398.362609,1,64.765647,1,55.997463,1
498,2020-10-19 08:00:00,11477.00,11401.787826,1,66.052030,1,57.103365,1
499,2020-10-19 12:00:00,11650.15,11407.406087,1,69.299820,1,67.521533,1

In [147]:
df['position'] = df['SMA_pos'] + df['MFI_pos'] + df['RSI_pos']

df[['SMA_pos','MFI_pos','RSI_pos','position']].tail(10)

     SMA_pos  MFI_pos  RSI_pos  position
490        0        0        0         0
491        1        0        1         2
492        1        0        0         1
493        1        1        1         3
494        1        1        1         3
495        1        1        1         3
496        1        1        0         2
497        1        1        1         3
498        1        1        1         3
499        1        1        1         3

In [150]:
print (df[['# openTime','position']].iloc[-2])

# openTime    2020-10-19 08:00:00
position                        3
Name: 498, dtype: object