In [1]:
import pandas as pd
import pandas_ta as ta

# Load data
df = pd.read_csv("./BTCUSDT_4h.csv")

# appending CMO 14 to the DataFrame
df.ta.cmo(length=14, append=True)

df[['# openTime', 'open', 'high', 'low', 'close', 'volume','CMO_14']].tail(10)

,# openTime,open,high,low,close,volume,CMO_14
490,1602979200000,11360.31,11398.00,11346.22,11368.02,3109.800004,2.635176
491,1602993600000,11368.02,11464.99,11366.87,11455.40,4133.080675,16.239584
492,1603008000000,11455.40,11477.96,11398.41,11420.62,3767.885698,9.702631
493,1603022400000,11420.62,11482.24,11407.61,11446.68,5024.660598,13.603192
494,1603036800000,11447.05,11478.47,11429.88,11432.24,3461.610905,10.762649
495,1603051200000,11432.23,11505.00,11413.96,11503.14,3787.003311,21.136269
496,1603065600000,11503.14,11535.00,11407.96,11416.71,5106.702706,5.168289
497,1603080000000,11416.25,11467.10,11407.96,11462.39,4137.008630,11.755312
498,1603094400000,11462.39,11532.01,11447.23,11477.00,5876.872361,13.806924
499,1603108800000,11477.00,11671.81,11472.46,11650.15,8515.296375,33.452822